
bag_dirs: "/media/david/PortableSSD/data/Rosbags/NewerCollege/2021-07-01-10-40-50_0-stairs.bag"

# input
lidar_topic: "/os1_cloud_node/points"
imu_topic: "/os1_cloud_node/imu"

# output: save resulting poses and point cloud
# pose format: [timestamp_s tx ty tz qx qy qz qw]
result_dir: "/home/david/optim"


## LiDAR config ##

# sensor ["hesai","ouster"]
sensor: "ouster"

# clock time shift
timeshift_lidar2imu: 0.000

## imu setting ##
use_imu: true
sigma_gyr: 0.01
sigma_acc: 0.3

# extrinsic imu2lidar #
# rot quaternion
q_x: 0.000
q_y: 0.000
q_z: 0.000
q_w: 1.000

# translation
t_x: 0.0
t_y: 0.0
t_z: 0.0

